// src/components/Footer.jsx
import React from 'react';
import Social from './Social';

const Footer = () => {
    return (
        <footer className="bg-black py-8 border-t border-gray-800">
            <div className="container mx-auto px-6 flex flex-col md:flex-row justify-between items-center">
                <div className="text-gray-400 mb-4 md:mb-0">
                    &copy; {new Date().getFullYear()} Pranjalya Tiwari
                </div>
                <div className="text-gray-500 text-sm mb-4 md:mb-0 text-center">
                    Cover Image: Hubble Ultra Deep Field
                </div>
                <Social />
            </div>
        </footer>
    );
};

export default Footer;

// src/components/Footer.vue
<template>
  <footer class="footer">
    <div>&copy; 2020 Pranjalya Tiwari</div>
    <div>Cover Image : Hubble Ultra Deep Field, courtesy of Hubble Telescope</div>
    <Social />
  </footer>
</template>

<script>
import Social from "./Social";

export default {
  name: "Footer",
  components: {
    Social
  }
};
</script>

<style scoped lang="scss">
@import "@/styles/variables.scss";

$bg-footer: map-get($colors, dark) !default;

.footer {
  padding: 5px 20px 0 20px;
  background-color: $bg-footer;
  color: map-get($colors, light);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

/deep/ .social-wrap {
  float: right;

  i {
    font-size: 2.4rem;

    &:hover {
      color: map-get($colors, light);
    }
  }
}
</style>
